### ISSUE TITLE
Nieoczekiwany błąd dla Promise (nie jest zdefiniowany)

### ISSUE THREAD

**Issue by debian-sh** [groovy354/Sealious#99]
Przy próbie odpalenia własnej aplikacji:

arkadiusz@arkadiusz-ThinkPad-X200:~/Pulpit/placetag-app$ sudo sealious .
/home/arkadiusz/Projects/Sealious/base-chips
/home/arkadiusz/Pulpit/placetag-app/modules/placetag
initializing module base_chips
initializing module placetag

/home/arkadiusz/Projects/Sealious/lib/chip-types/chip.js:25
		return new Promise(function(resolve, reject){
		           ^
ReferenceError: Promise is not defined
    at start (/home/arkadiusz/Projects/Sealious/lib/chip-types/chip.js:25:14)
    at /home/arkadiusz/Projects/Sealious/lib/chip-types/chip-manager.js:91:25
    at Array.forEach (native)
    at start_chips_from_module (/home/arkadiusz/Projects/Sealious/lib/chip-types/chip-manager.js:88:18)
    at start (/home/arkadiusz/Projects/Sealious/lib/module/module.js:163:30)
    at start (/home/arkadiusz/Projects/Sealious/lib/module/module-manager.js:106:25)
    at start (/home/arkadiusz/Projects/Sealious/lib/core.js:81:17)
    at Object.<anonymous> (/home/arkadiusz/Projects/Sealious/shell.js:18:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

**Comment by groovy354** [comment]
Hmm problem polegał na tym, że  u mnie Promis jest zdefiniowany, bo mam najnowszego node'a (kompilowany ze źródeł). Dodałem linijkę, która wczytuje polyfill dla starszych wersjo node (`bluebird`). Zcheckoutuj się na `dev` i sprawdź, czy problem nadal występuje. Jeżeli tak, to otwórz tego issue ponownie.

**Comment by debian-sh** [comment]
Hmm, działa (jest console.log, który dodałeś, nazwa jest wczytana z configu) niemniej jednak baza nie jest automatycznie tworzona. 

![selection_009](https://cloud.githubusercontent.com/assets/5663277/6564392/67de3b2e-c6a8-11e4-8796-c1235f50ee96.png)
